title: Battle Nation Live
author: BattleNationLive
email: battlenationlive@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Battle Nation Live

twitter_username: battle_nation_l
github_username:  BattleNationLive

google_analytics: UA-116668768-1

sass:
    style: compressed

plugins:
  - jekyll-sitemap